authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView


app_name = 'authentication'

urlpatterns = [
    path('', views.authentication, name='authentication'),
    path('home', views.home, name="home"),
    path('chat', views.chat, name="chat"),
    path('profile', views.profile, name="profile"),
    path('signup', views.signup, name="signup"),
    path('signin', views.signin, name="signin"),
    path('signout', views.signout, name="signout"),
    path('videochat', views.videochat, name="videochat"),
    path('changepassword', views.changepassword, name="changepassword"),
    path('myprofile', views.my_profile, name='myprofile'),
    path('my_invites', views.invites_received_view, name="my_invites"),
    path('all-profiles', ProfileListView.as_view(), name='all-profile-view'),
    path('to-invite', views.invite_profiles_list_view, name='invite-profile-view'),
    path('send_invite', views.send_invatation, name='send_invite'),
    path('remove_friend', views.remove_from_friends, name='remove_friend'),
    path('accept_invatation', views.accept_invatation, name='accept_invatation'),
    path('reject_invatation', views.reject_invatation, name='reject_invatation'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='password-reset/change-password.html',
            success_url='/'
        ),
        name='change_password'
    ),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='password-reset/password_reset.html',
             email_template_name='password-reset/password_reset_email.html',
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webchatapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
]

templates/activation_failed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    fail
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock title %}
    <!----======== CSS ======== -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <!----===== Boxicons CSS ===== -->
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>

    <!--<title>Dashboard Sidebar Menu</title>--> 
</head>
<body>
    <nav class="sidebar close">
        <header>
            <div class="image-text">
                <span class="image">
                    <img src="https://cdn-icons-png.flaticon.com/512/3114/3114649.png" alt="">
                </span>

                <div class="text logo-text">
                    <span class="name">Talk That Talk</span>
                    <span class="profession">Chat with strangers</span>
                </div>
            </div>

            <i class='bx bx-chevron-right toggle'></i>
        </header>

        <div class="menu-bar">
            <div class="menu">

                <ul class="menu-links">
                    <li class="nav-link">
                        <a href="/home">
                            <i class='bx bx-home-alt icon' ></i>
                            <span class="text nav-text">Home</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="/chat">
                            <i class='bx bx-chat icon'></i>
                            <span class="text nav-text">Chat</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="/profile">
                            <i class='bx bx-user-circle icon'></i>
                            <span class="text nav-text">Profile</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="/change-password">
                            <i class='bx bx-lock-alt icon'></i>
                            <span class="text nav-text">Change Password</span>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="bottom-content">
                <li class="">
                    <a href="/signout">
                        <i class='bx bx-log-out icon' ></i>
                        <span class="text nav-text">Logout</span>
                    </a>
                </li>

                <li class="mode">
                    <div class="sun-moon">
                        <i class='bx bx-moon icon moon'></i>
                        <i class='bx bx-sun icon sun'></i>
                    </div>
                    <span class="mode-text text">Dark mode</span>

                    <div class="toggle-switch">
                        <span class="switch"></span>
                    </div>
                </li>
                
            </div>
        </div>

    </nav>

    <section class="home">
        {% block content %} {% endblock %}
    </section>

    <script>
        const body = document.querySelector('body'),
      sidebar = body.querySelector('nav'),
      toggle = body.querySelector(".toggle"),

      modeSwitch = body.querySelector(".toggle-switch"),
      modeText = body.querySelector(".mode-text");


toggle.addEventListener("click" , () =>{
    sidebar.classList.toggle("close");
})



modeSwitch.addEventListener("click" , () =>{
    body.classList.toggle("dark");
    
    if(body.classList.contains("dark")){
        modeText.innerText = "Light mode";
    }else{
        modeText.innerText = "Dark mode";
        
    }
});
    </script>

</body>
</html>

templates/chat.html
{% extends 'base.html' %}
{% block title %}Chat{% endblock title %}
{% load static %}
{% block content %}
{% comment %} <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>{% endcomment %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" rel="stylesheet" /> 
<link rel="stylesheet" href="{% static 'css/chat.css' %}">
<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css'>
<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.2/css/font-awesome.min.css'>
{% comment %} <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"> {% endcomment %}
<div id="frame">
	<div id="sidepanel">
		<div id="profile">
			<div class="wrap">
                <a href="profile"><img id="profile-img" src="{{data.avatar.url}}" class="online" alt=""></a>
				
				<p>{{user_name}}</p>
				<i class="fa fa-chevron-down expand-button" aria-hidden="true"></i>
				<div id="status-options">
					<ul>
						<li id="status-online" class="active"><span class="status-circle"></span> <p>Online</p></li>
						<li id="status-away"><span class="status-circle"></span> <p>Away</p></li>
						<li id="status-busy"><span class="status-circle"></span> <p>Busy</p></li>
						<li id="status-offline"><span class="status-circle"></span> <p>Offline</p></li>
					</ul>
				</div>
				<div id="expanded">
					<label for="twitter"><i class="fa fa-facebook fa-fw" aria-hidden="true"></i></label>
					<input name="twitter" type="text" value="mikeross" />
					<label for="twitter"><i class="fa fa-twitter fa-fw" aria-hidden="true"></i></label>
					<input name="twitter" type="text" value="ross81" />
					<label for="twitter"><i class="fa fa-instagram fa-fw" aria-hidden="true"></i></label>
					<input name="twitter" type="text" value="mike.ross" />
				</div>
			</div>
		</div>
		<div id="search">
			<label for=""><i class="fa fa-search" aria-hidden="true"></i></label>
			<input type="text" placeholder="Search contacts..." />
		</div>
		{% comment %} <div id="contacts">
			<ul>
				{% comment %} <li class="contact">
					<div class="wrap">
						<span class="contact-status online"></span>
						<img src="http://emilcarlsson.se/assets/louislitt.png" alt="" />
						<div class="meta">
							<p class="name">Louis Litt</p>
							<p class="preview">You just got LITT up, Mike.</p>
						</div>
					</div>
				</li>
				<li class="contact active">
					<div class="wrap">
						<span class="contact-status busy"></span>
						<img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="" />
						<div class="meta">
							<p class="name">Harvey Specter</p>
							<p class="preview">Wrong. You take the gun, or you pull out a bigger one. Or, you call their bluff. Or, you do any one of a hundred and forty six other things.</p>
						</div>
					</div>
				</li>
				<li class="contact">
					<div class="wrap">
						<span class="contact-status away"></span>
						<img src="http://emilcarlsson.se/assets/rachelzane.png" alt="" />
						<div class="meta">
							<p class="name">Rachel Zane</p>
							<p class="preview">I was thinking that we could have chicken tonight, sounds good?</p>
						</div>
					</div>
				</li>
				<li class="contact">
					<div class="wrap">
						<span class="contact-status online"></span>
						<img src="http://emilcarlsson.se/assets/donnapaulsen.png" alt="" />
						<div class="meta">
							<p class="name">Donna Paulsen</p>
							<p class="preview">Mike, I know everything! I'm Donna..</p>
						</div>
					</div>
				</li>
				<li class="contact">
					<div class="wrap">
						<span class="contact-status busy"></span>
						<img src="http://emilcarlsson.se/assets/jessicapearson.png" alt="" />
						<div class="meta">
							<p class="name">Jessica Pearson</p>
							<p class="preview">Have you finished the draft on the Hinsenburg deal?</p>
						</div>
					</div>
				</li>
				<li class="contact">
					<div class="wrap">
						<span class="contact-status"></span>
						<img src="http://emilcarlsson.se/assets/haroldgunderson.png" alt="" />
						<div class="meta">
							<p class="name">Harold Gunderson</p>
							<p class="preview">Thanks Mike! :)</p>
						</div>
					</div>
				</li>
				<li class="contact">
					<div class="wrap">
						<span class="contact-status"></span>
						<img src="http://emilcarlsson.se/assets/danielhardman.png" alt="" />
						<div class="meta">
							<p class="name">Daniel Hardman</p>
							<p class="preview">We'll meet again, Mike. Tell Jessica I said 'Hi'.</p>
						</div>
					</div>
				</li>
				<li class="contact">
					<div class="wrap">
						<span class="contact-status busy"></span>
						<img src="http://emilcarlsson.se/assets/katrinabennett.png" alt="" />
						<div class="meta">
							<p class="name">Katrina Bennett</p>
							<p class="preview">I've sent you the files for the Garrett trial.</p>
						</div>
					</div>
				</li>
				<li class="contact">
					<div class="wrap">
						<span class="contact-status"></span>
						<img src="http://emilcarlsson.se/assets/charlesforstman.png" alt="" />
						<div class="meta">
							<p class="name">Charles Forstman</p>
							<p class="preview">Mike, this isn't over.</p>
						</div>
					</div>
				</li>
				<li class="contact">
					<div class="wrap">
						<span class="contact-status"></span>
						<img src="http://emilcarlsson.se/assets/jonathansidwell.png" alt="" />
						<div class="meta">
							<p class="name">Jonathan Sidwell</p>
							<p class="preview"><span>You:</span> That's bullshit. This deal is solid.</p>
						</div>
					</div>
				</li> {% endcomment %}
			</ul>
		</div> 

	</div>
	<div class="content">
		<div class="contact-profile">
			{% comment %} <img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="" /> {% endcomment %}
			<div class="social-media">
				<i class="addfr fa-solid fa-user-plus" aria-hidden="true">
					<span class="tooltiptext">Add friends</span>
				</i>
				
			</div>
			
		</div>
		<div class="messages">
			<ul  id="history">
			</ul>
		</div>
		<div class="message-input">
			<div class="wrap">
			<input type="text" placeholder="Write your message..." id="message"/>
			<i class="fa fa-paperclip attachment" aria-hidden="true"></i>
			<button class="submit" id="send"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
			</div>
		</div>
	</div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
<script>
	var userid = {{user_name.id}};
	var peid = null;
	var username = "{{user_name}}"
	window.CSRF_TOKEN = "{{ csrf_token }}"; 
</script>
<script src="{% static 'js/peer.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
<script src="{% static 'js/peer-client.js' %}"></script>
{% endblock %}

templates/email_confirmation.html
{% autoescape off %}

 Welcome to Chat App Login!!
 Hello {{ name }}!!
 Please confirm your email by clicking on the following link.

 Confirmation Link: http://{{ domain }}{% url 'activate' uidb64=uid token=token %} 

 {% endautoescape %}

templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">

<div class="text-home">
    <h2>Welcome Back, {{user_name}}</h2>
    <img class="img-home" src="https://media3.giphy.com/media/mBSeE1Q3yxcb0XoSKh/giphy.gif?cid=ecf05e47o1yy4m1m4xy1y5piokbbz8atgrvrvvhvrxnxnv0v&rid=giphy.gif&ct=s" alt="logo">
    <h4>Start Conversation with your contacts</h4>
    <p>Brightened when I saw your face <br>
    All I can say is, it was enchanting to meet you,</p>
    <div class="button">
        <a href="/videochat" class="btn btn-primary">Meet Now</a>
        <a href="/chat" class="btn btn-light">Start Chat</a>
    </div>
</div>


{% endblock %}

templates/my_invites.html
{% extends 'base.html' %}

{% block title %}
my invites
{% endblock title %}

{% block content %}

    {% if is_empty %}
        <h1>No invatations here..</h1>
    {% endif %}
 
    {% for obj in qs %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <br>
                        <a href="">
                            <button class="ui primary button w-big mb-5">See profile</button>
                        </a>
                        <form action="{% url 'authentication:accept_invatation' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui positive basic button w-big mb-5">
                                <i class="check icon"></i>
                                Accept invite
                            </button>
                        </form>
                         <form action="{% url 'authentication:reject_invatation' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button w-big mb-5">
                                <i class="close icon"></i>
                                Reject invite
                            </button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    {% endfor %}

{% endblock content %}

templates/myprofile.html
{% extends 'base.html'%}
{% block title %}
my Profile
{% endblock %}
{% block content %}
<h1 style="magin : 10dx"> Profile of: {{request.user}}</h1>
    {% for friend in profile.get_friends %}
        {{friend}}
        <br>

    {% endfor %}
    Friend number: {{profile.get_friends_no}}
{% endblock content %}

templates/profile_list.html
{% extends 'base.html' %}

{% block title %}
all profiles
{% endblock title %}

{% block content %}

    {% if is_empty %}
        <h1>No profiles to interact with</h1>
    {% endif %}

    {% for obj in object_list %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href={{obj.get_absolute_url}}><button class="ui primary button mb-5 w-big">See profile</button></a>
                        <br>

                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                            <form action="{% url 'authentication:send_invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                            </form>
                         {% endif %}

                        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                            <button  class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                        {% endif %}

                        {% if request.user in obj.friends.all %}
                        <form action="{% url 'authentication:remove_friend' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                        </form>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

templates/to_invite_list.html
{% extends 'base.html' %}

{% block title %}
invites friend
{% endblock title %}

{% block content %}
<ul>
{% for item  in  qs %}
<li>{{item}}</li>
{% endfor %}
</ul>
{% endblock content %}

templates/videochat.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/videochat.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Video Call</title>
</head>
<body>
    <div class="header">
        <div class="row">
            <div class="col1">
                <video id="their-video" muted="" autoplay=""></video>
                <div class="contarols">
                    {% comment %} <button id="next">Next</button> {% endcomment %}
                    <i id="next" class="fas fa-angles-right">
                        <span class="tooltiptext">Another friend</span></i>
                    <i id="mute-mic" class="fas fa-microphone"></i>
                    <a href="/home"><i class="fas fa-phone" style="color:#f41919; border-radius: 50%; font-size:35px; "></i></a>
                    <i id="mute-video" class="fas fa-video" style="font-size:28px; "></i>
                    <i id="find" class="fas fa-search">
                        <span class="tooltiptext">Find friend</span>
                    </i>
                    {% comment %} <button id="find">Find</button> {% endcomment %}
                </div>
            </div>
            <div class="col2">
                <div class="yourcamera">
                    <p>You</p>
                    <div>
                        <video id="my-video" muted="" autoplay=""></video>
                    </div>
                </div>
            </div>
        </div>
    </div>   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
    <script>
        var username = "{{user_name}}"
    </script>
    <script src="{% static 'js/peer.js' %}"></script>
    <script src="{% static 'js/app-video.js' %}"></script>
    <script src="{% static 'js/peer-client-video.js' %}"></script>
</body>
</html>